### PR TITLE
User readable message on permission error in tmp directory

### LINKED ISSUE #1: If the perk command fails due to bad permissions it fails silently
Add an error notifying if the permissions on the `node_modules/perk-cli` directory are wrong.

### To reproduce this bug...

1. Fork and clone this repo.
1. Uninstall the `perk-cli` if you currently have it installed.
1. cd into the cloned directory and `npm install`.
1. run the command `npm link` to link the `perk` command to the code in this directory.
1. run `sudo chmod -R 555 dist/tmp` to mimic incorrect permissions on the directory where the perk boilerplate code is supposed to be downloaded.
1. Try to use the perk command in another directory. Notice that it doesn't work, but it also doesn't give any warnings or errors.

### To fix...

It looks like there's an error in the overall [catch handler](https://github.com/alarner/perk-cli/blob/master/src/index.js#L33). It appears to be trying to reference a variable message, which doesn't exist.

### To test

You should make your changes in the `src` directory. Once you're ready to test changes, run `npm run build` to rebuild the src code in the `dist` directory. Then you can run the `perk` command and see if your changes work. We're not going to be able to actually change file permissions, so success in this case is just displaying the proper error.

### PR DESCRIPTION
**Pull request by RobAWilkinson**
closes #1 
Not sure how to test for this other than writing some manual script. 

Maybe have a fixture folder with bad permissions that we mock as `TMP` when we run the test?

### CODE REVIEW

**Comment by alarner** [comment]
@RobAWilkinson thanks so much for the PR! The code looks great, but the formatting looks slightly off. Would you mind switching spaces to tabs? Sorry not trying to be pedantic, just want to keep consistency. If it's a hassle I'm happy to do it :)

**Comment by RobAWilkinson** [comment]
Sure no problem will do tonight.

**Comment by RobAWilkinson** [comment]
done!

**Comment by alarner** [comment]
Looks great 👍

**Pull request merged**
